name: Test Project Workflow

on:
  push:
    branches: [master]
    paths:
      - 'biocypher_metta/adapters/**'
      - 'biocypher_metta/metta_writer.py'
      - 'config/adapters_config.yaml'
      - 'create_knowledge_graph.py'
  pull_request:
    branches: [master]
    paths:
      - 'biocypher_metta/adapters/**'
      - 'biocypher_metta/metta_writer.py'
      - 'config/adapters_config.yaml'
      - 'create_knowledge_graph.py'

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      adapters_changed: ${{ steps.check_outputs.outputs.adapters_changed }}
      writer_changed: ${{ steps.check_outputs.outputs.writer_changed }}
      config_changed: ${{ steps.check_outputs.outputs.config_changed }}
      both_changed: ${{ steps.check_outputs.outputs.both_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine changed files
        id: check_outputs
        run: |
          adapters_changed=false
          writer_changed=false
          config_changed=false
          both_changed=false

          # Check for changed files between commits
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          echo "Changed files: $changed_files"

          if echo "$changed_files" | grep -q 'biocypher_metta/adapters/'; then
            adapters_changed=true
          fi

          if echo "$changed_files" | grep -q 'biocypher_metta/metta_writer.py'; then
            writer_changed=true
          fi

          if echo "$changed_files" | grep -q 'config/adapters_config.yaml'; then
            config_changed=true
          fi

          if [[ "$writer_changed" == true && "$config_changed" == true ]]; then
            both_changed=true
          fi

          echo "adapters_changed=$adapters_changed" >> $GITHUB_OUTPUT
          echo "writer_changed=$writer_changed" >> $GITHUB_OUTPUT
          echo "config_changed=$config_changed" >> $GITHUB_OUTPUT
          echo "both_changed=$both_changed" >> $GITHUB_OUTPUT

  run-tests:
    needs: determine-changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust based on your project structure
          
      # Handle the case where both writer and config have changed
      - name: Run tests when both writer and config changed
        if: needs.determine-changes.outputs.both_changed == 'true'
        run: |
          echo "Both writer and config changed. Running all adapters."
          python run_all_adapters.py --writer updated_writer  # Adjust the test command as per your logic

      # Run appropriate tests based on changes in writer, config, or adapters
      - name: Run specific tests
        if: needs.determine-changes.outputs.both_changed != 'true'
        run: |
          if [[ "${{ needs.determine-changes.outputs.writer_changed }}" == "true" ]]; then
            echo "Writer changed. Running all adapters."
            python run_all_adapters.py
          elif [[ "${{ needs.determine-changes.outputs.config_changed }}" == "true" ]]; then
            echo "Config changed. Running affected adapters."
            python run_affected_adapters.py --config updated_config.yml
          elif [[ "${{ needs.determine-changes.outputs.adapters_changed }}" == "true" ]]; then
            echo "Adapters changed. Running only the changed adapters."
            python run_changed_adapters.py
          else
            echo "No significant changes detected. Skipping tests."
